
#!/usr/bin/env node

const fs = require('fs')
const readline = require('readline')
const path = require('path')

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
})

function askQuestion(question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer)
    })
  })
}

async function setupEnvironment() {
  console.log('🚀 Welcome to Eboni Dating Environment Setup!\n')
  
  const envVars = {}
  
  // Supabase Configuration
  console.log('📊 Supabase Configuration:')
  envVars.NEXT_PUBLIC_SUPABASE_URL = await askQuestion('Enter your Supabase URL: ')
  envVars.NEXT_PUBLIC_SUPABASE_ANON_KEY = await askQuestion('Enter your Supabase Anon Key: ')
  envVars.SUPABASE_SERVICE_ROLE_KEY = await askQuestion('Enter your Supabase Service Role Key: ')
  envVars.DATABASE_URL = await askQuestion('Enter your Database URL (optional): ') || ''
  
  // Authentication
  console.log('\n🔐 Authentication Configuration:')
  envVars.NEXT_PUBLIC_JWT_SECRET = await askQuestion('Enter JWT Secret (32+ characters): ') || 
    'your_jwt_secret_' + Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15)
  
  // Site Configuration
  console.log('\n🌐 Site Configuration:')
  envVars.NEXT_PUBLIC_SITE_URL = await askQuestion('Enter your site URL (e.g., https://your-app.vercel.app or https://your-app.replit.app): ') || 'http://localhost:5000'
  
  // Email Configuration
  console.log('\n📧 Email Configuration (SendGrid):')
  envVars.SENDGRID_API_KEY = await askQuestion('Enter SendGrid API Key (optional): ') || ''
  envVars.SENDGRID_FROM_EMAIL = await askQuestion('Enter from email (optional): ') || 'noreply@your-domain.com'
  
  // Stripe Configuration
  console.log('\n💳 Stripe Configuration:')
  envVars.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = await askQuestion('Enter Stripe Publishable Key (optional): ') || ''
  envVars.STRIPE_SECRET_KEY = await askQuestion('Enter Stripe Secret Key (optional): ') || ''
  
  // Google OAuth
  console.log('\n📱 Google OAuth (optional):')
  envVars.GOOGLE_CLIENT_ID = await askQuestion('Enter Google Client ID (optional): ') || ''
  envVars.GOOGLE_CLIENT_SECRET = await askQuestion('Enter Google Client Secret (optional): ') || ''
  
  // Generate .env.local file
  let envContent = '# Generated by setup-env.js\n# ' + new Date().toISOString() + '\n\n'
  
  envContent += '# Supabase Configuration\n'
  envContent += `NEXT_PUBLIC_SUPABASE_URL=${envVars.NEXT_PUBLIC_SUPABASE_URL}\n`
  envContent += `NEXT_PUBLIC_SUPABASE_ANON_KEY=${envVars.NEXT_PUBLIC_SUPABASE_ANON_KEY}\n`
  envContent += `SUPABASE_SERVICE_ROLE_KEY=${envVars.SUPABASE_SERVICE_ROLE_KEY}\n`
  if (envVars.DATABASE_URL) envContent += `DATABASE_URL=${envVars.DATABASE_URL}\n`
  
  envContent += '\n# Authentication\n'
  envContent += `NEXT_PUBLIC_JWT_SECRET=${envVars.NEXT_PUBLIC_JWT_SECRET}\n`
  
  envContent += '\n# Site Configuration\n'
  envContent += `NEXT_PUBLIC_SITE_URL=${envVars.NEXT_PUBLIC_SITE_URL}\n`
  envContent += `NEXT_PUBLIC_APP_NAME=Dating Platform\n`
  envContent += `NEXT_PUBLIC_APP_DESCRIPTION=Modern dating and modeling platform\n`
  
  if (envVars.SENDGRID_API_KEY) {
    envContent += '\n# Email Configuration\n'
    envContent += `SENDGRID_API_KEY=${envVars.SENDGRID_API_KEY}\n`
    envContent += `SENDGRID_FROM_EMAIL=${envVars.SENDGRID_FROM_EMAIL}\n`
    envContent += `SENDGRID_FROM_NAME=Eboni Dating\n`
  }
  
  if (envVars.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY) {
    envContent += '\n# Stripe Configuration\n'
    envContent += `NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${envVars.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}\n`
    envContent += `STRIPE_SECRET_KEY=${envVars.STRIPE_SECRET_KEY}\n`
  }
  
  if (envVars.GOOGLE_CLIENT_ID) {
    envContent += '\n# Google OAuth\n'
    envContent += `GOOGLE_CLIENT_ID=${envVars.GOOGLE_CLIENT_ID}\n`
    envContent += `GOOGLE_CLIENT_SECRET=${envVars.GOOGLE_CLIENT_SECRET}\n`
  }
  
  envContent += '\n# Production Settings\n'
  envContent += `NODE_ENV=production\n`
  envContent += `NEXT_PUBLIC_DEBUG=false\n`
  envContent += `BCRYPT_ROUNDS=12\n`
  
  // Write to file
  fs.writeFileSync('.env.local', envContent)
  
  console.log('\n✅ Environment file created successfully!')
  console.log('📁 File location: .env.local')
  console.log('\n🔒 Remember to:')
  console.log('1. Never commit .env.local to git')
  console.log('2. Add these variables to Replit Secrets for deployment')
  console.log('3. Update your Supabase project settings')
  console.log('4. Configure your domain in Supabase Auth settings')
  
  rl.close()
}

setupEnvironment().catch(console.error)
